version: '3.5'

services:
  go:
    build: .
    depends_on:
      - db
    ports:
      - 8000:80
    volumes:
      - .:/go/src/app

  db:
    image: postgres:11.3-alpine
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_DB: db_name
      POSTGRES_PASSWORD: db_password

