CREATE TABLE beer (
    ID INTEGER PRIMARY KEY NOT NULL,
    Name VARCHAR(255) NULL,
    ABV FLOAT NULL,
    BreweryID VARCHAR(255) NULL,
    BreweryName VARCHAR(255) NULL,
    City VARCHAR(255) NULL,
    Country VARCHAR(255) NULL,
    State VARCHAR(255) NULL
)
